---
title: "Trails Analysis"
output: word_document
---

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(support.CEs)
library(tidyverse)
library(pander)
library(flextable)
library(tidyverse)
library(mlogit) # for logistic regression
library(aod)
library(gmnl)
```


## Data Wrangling
```{r}
design_matrix <- read.csv("https://raw.githubusercontent.com/ryangifford/discrete_choice_experiment/master/Data/design_matrix.csv") # importing the matrix design (see matrix design file)

survey <- read.csv("https://raw.githubusercontent.com/ryangifford/discrete_choice_experiment/master/Data/Rexburg%20Trails_CE.csv")# %>% 
  select(c1:c9, res, id) %>% 
  pivot_longer(cols = starts_with("c"), names_to = "question_num", values_to = "Key")
  
  


# importing the survey data, selecting the choice experiment questions + resident status + id, 
# making each observatoin an individual row. Key is block num, question num, and alt. num. 

#dat <- right_join(design_matrix, survey, by = "Key")


#dat2 <- dat %>% 
 # mutate(I = str_extract(dat$Key, "^.{2}")) %>% 
 # mutate(Chose = str_sub(dat$Key, -1))

dat <- read.csv("https://raw.githubusercontent.com/ryangifford/discrete_choice_experiment/master/Data/FinalData.csv")


```


https://stats.idre.ucla.edu/r/dae/logit-regression/
```{r}


library(dfidx)


dat <- dat %>% 
  filter(ID != 42 & ID !=44 & ID != 46 & ID != 65)



MC <- dfidx(dat, idx = c("Case", "Alternative"), drop.index = FALSE)

MC <- dfidx(dat, idx = c("Case", "Alternative"), alt.levels = c(1, 2, 3))



ml.MC1 <- mlogit(Choice ~ Rail + Teton + Dirt + Gravel + Paved + Dist + Cost, 
                data = MC)


mylogit <- glm(Choice ~ Rail + Teton + Dirt + Gravel + Paved + Dist + Cost, 
                data = MC, binomial(link = "logit"))

summary(mylogit)



mylogit <- gmnl(Choice ~ Rail + Teton + Dirt + Gravel + Dist  + Paved+ Cost, 
                data = dat2)
```

## Plot

```{r eval = FALSE}
ggplot(newdata3, aes(x = gre, y = PredictedProb)) + geom_ribbon(aes(ymin = LL,
    ymax = UL, fill = rank), alpha = 0.2) + geom_line(aes(colour = rank),
    size = 1)

```

## Math Notations

$$U_n^i = V_n^i + \epsilon_n^i$$
$$V_n^i = \gamma_n + \lambda_nX_n^i$$
$$I^{th}$$
$$Prob[V_n^i + \epsilon_n^i \geq V_k^i + \epsilon_k^i; \forall \neq k$$
$$

## Tables 


### Choice Attribute Table

```{r table}
#dat <- read.csv("C:\\Users\\Ryan\\Desktop\\Choice Experiment\\discrete_choice_experiment\\Data\\choices.csv") 

dat_att <- read.csv("https://raw.githubusercontent.com/ryangifford/discrete_choice_experiment/master/Data/choices.csv") # this is a .csv with the all the attributes and levels



flextable(dat_att) %>% # this creates the table in word
  align(part = "all") %>% # left align
  set_caption(caption = "Rail Trail") %>% 
  font(fontname = "Times New Roman", part = "all") %>% 
  fontsize(size = 12, part = "body") %>% 
  # add footer if you want
  # add_footer_row(values = "* p < 0.05. ** p < 0.01. *** p < 0.001.", 
  #                colwidths = 4) %>% 
  theme_booktabs() %>% # default theme
  autofit() %>% 
  bg(i = c(1,3,5,7,9), bg = "#F7F7F7") %>% 
  hline(i = c(3,6))  %>% 
  vline(j = 2) %>% 
  add_header_row(
  values = c("Rail Trail", "Teton Trail"),
  colwidths = c(2, 2)) %>% 
  align(align = "center", part = "header") %>% 
  line_spacing(space = .5, part = "all")
```

```{r}



dat_key <- read.csv("https://raw.githubusercontent.com/ryangifford/discrete_choice_experiment/master/Data/Coding%20Key.csv") # this is a .csv with the all the attributes and levels



flextable(dat_key) %>% # this creates the table in word
  align(part = "all") %>% # left align
  set_caption(caption = "Rail Trail") %>% 
  font(fontname = "Times New Roman", part = "all") %>% 
  fontsize(size = 12, part = "body") %>% 
  # add footer if you want
  # add_footer_row(values = "* p < 0.05. ** p < 0.01. *** p < 0.001.", 
  #                colwidths = 4) %>% 
  theme_booktabs() %>% # default theme
  autofit() %>% 
  bg(i = c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29), bg = "#F7F7F7") %>% 
  hline(i = c(3,9,11,17))  %>% 
  vline(j = c(1,2,3,4,5)) %>% 
  align(align = "center", part = "header") %>% 
  line_spacing(space = .5, part = "all")
  
```