---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(tidyverse)
library(AlgDesign)
library(pander)
library(knitr)
library(xtable)
library(kableExtra)

```




```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

teton <-  expand.grid(
  Surface = c("Paved", "Gravel", "Dirt"),
  Location = c("HWY 20 to Eagle Park (0.36 miles)", "Eagle Park to Railroad (0.68 miles)", "Business Park to Canal (0.91 miles)" ),
  Cost = c("20", "37", "49")
  ) # Creating the choice sets


#teton$Cost <- sample(teton$Cost) # randomizing the columns

set.seed(69)

teton_output <- optFederov(~., data = teton , nTrials = 9)

#######################################

rail <-  expand.grid(
  Surface = c("Paved", "Gravel", "Dirt"),
  Location = c("Poleline to 4th S. (1.63 miles)", "4th S. to Riverside Park (1.50 miles)", "Riverside Park to 2nd E. (0.49 miles)") ,
   Cost = c("88", "81", "26"))
  
  

set.seed(69)

rail_output <- optFederov(~., data = rail , nTrials = 9)





pander(rail_output)
pander




####
sets <-  expand.grid(
  system = c("teton", "rail"),
  Surface = c("Paved", "Gravel", "Dirt"),
  Location = c("A","B","C") ,
   Cost = c("88", "81", "26"))
  
  

set.seed(69)

sets_output <- optFederov(~., data = sets , nTrials = 8)

sets_output
```


